//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class glue_schema_registry_serializer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal glue_schema_registry_serializer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(glue_schema_registry_serializer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(glue_schema_registry_serializer obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~glue_schema_registry_serializer() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GsrSerDePINVOKE.delete_glue_schema_registry_serializer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public glue_schema_registry_serializer(SWIGTYPE_p_p_glue_schema_registry_error p_err) : this(GsrSerDePINVOKE.new_glue_schema_registry_serializer(SWIGTYPE_p_p_glue_schema_registry_error.getCPtr(p_err)), true) {
  }

  public mutable_byte_array encode(read_only_byte_array array, string transport_name, glue_schema_registry_schema gsr_schema, SWIGTYPE_p_p_glue_schema_registry_error p_err) {
    global::System.IntPtr cPtr = GsrSerDePINVOKE.glue_schema_registry_serializer_encode(swigCPtr, read_only_byte_array.getCPtr(array), transport_name, glue_schema_registry_schema.getCPtr(gsr_schema), SWIGTYPE_p_p_glue_schema_registry_error.getCPtr(p_err));
    mutable_byte_array ret = (cPtr == global::System.IntPtr.Zero) ? null : new mutable_byte_array(cPtr, true);
    if (GsrSerDePINVOKE.SWIGPendingException.Pending) throw GsrSerDePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
