//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class glue_schema_registry_deserializer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal glue_schema_registry_deserializer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(glue_schema_registry_deserializer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~glue_schema_registry_deserializer() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GsrSerDePINVOKE.delete_glue_schema_registry_deserializer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public glue_schema_registry_deserializer(SWIGTYPE_p_p_glue_schema_registry_error p_err) : this(GsrSerDePINVOKE.new_glue_schema_registry_deserializer__SWIG_0(SWIGTYPE_p_p_glue_schema_registry_error.getCPtr(p_err)), true) {
  }

  public glue_schema_registry_deserializer(string config_file_path, SWIGTYPE_p_p_glue_schema_registry_error p_err) : this(GsrSerDePINVOKE.new_glue_schema_registry_deserializer__SWIG_1(config_file_path, SWIGTYPE_p_p_glue_schema_registry_error.getCPtr(p_err)), true) {
  }

  public mutable_byte_array decode(read_only_byte_array array, SWIGTYPE_p_p_glue_schema_registry_error p_err) {
    global::System.IntPtr cPtr = GsrSerDePINVOKE.glue_schema_registry_deserializer_decode(swigCPtr, read_only_byte_array.getCPtr(array), SWIGTYPE_p_p_glue_schema_registry_error.getCPtr(p_err));
    mutable_byte_array ret = (cPtr == global::System.IntPtr.Zero) ? null : new mutable_byte_array(cPtr, true);
    if (GsrSerDePINVOKE.SWIGPendingException.Pending) throw GsrSerDePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool can_decode(read_only_byte_array array, SWIGTYPE_p_p_glue_schema_registry_error p_err) {
    bool ret = GsrSerDePINVOKE.glue_schema_registry_deserializer_can_decode(swigCPtr, read_only_byte_array.getCPtr(array), SWIGTYPE_p_p_glue_schema_registry_error.getCPtr(p_err));
    if (GsrSerDePINVOKE.SWIGPendingException.Pending) throw GsrSerDePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public glue_schema_registry_schema decode_schema(read_only_byte_array array, SWIGTYPE_p_p_glue_schema_registry_error p_err) {
    global::System.IntPtr cPtr = GsrSerDePINVOKE.glue_schema_registry_deserializer_decode_schema(swigCPtr, read_only_byte_array.getCPtr(array), SWIGTYPE_p_p_glue_schema_registry_error.getCPtr(p_err));
    glue_schema_registry_schema ret = (cPtr == global::System.IntPtr.Zero) ? null : new glue_schema_registry_schema(cPtr, true);
    if (GsrSerDePINVOKE.SWIGPendingException.Pending) throw GsrSerDePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
