//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class GsrSerDe {
  public static int glue_schema_registry_set_config_file(string config_file_path, SWIGTYPE_p_p_glue_schema_registry_error p_err) {
    int ret = GsrSerDePINVOKE.glue_schema_registry_set_config_file(config_file_path, SWIGTYPE_p_p_glue_schema_registry_error.getCPtr(p_err));
    return ret;
  }

}
