//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class mutable_byte_array : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal mutable_byte_array(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(mutable_byte_array obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~mutable_byte_array() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GsrSerDePINVOKE.delete_mutable_byte_array(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public mutable_byte_array(uint len, SWIGTYPE_p_p_glue_schema_registry_error p_err) : this(GsrSerDePINVOKE.new_mutable_byte_array(len, SWIGTYPE_p_p_glue_schema_registry_error.getCPtr(p_err)), true) {
  }

  public void get_data_copy(byte[] data) {
    GsrSerDePINVOKE.mutable_byte_array_get_data_copy(swigCPtr, data);
  }

  public SWIGTYPE_p_unsigned_char get_data() {
    global::System.IntPtr cPtr = GsrSerDePINVOKE.mutable_byte_array_get_data(swigCPtr);
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public uint get_max_len() {
    uint ret = GsrSerDePINVOKE.mutable_byte_array_get_max_len(swigCPtr);
    return ret;
  }

}
