# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_GsrSerDePyGen')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_GsrSerDePyGen')
    _GsrSerDePyGen = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_GsrSerDePyGen', [dirname(__file__)])
        except ImportError:
            import _GsrSerDePyGen
            return _GsrSerDePyGen
        try:
            _mod = imp.load_module('_GsrSerDePyGen', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _GsrSerDePyGen = swig_import_helper()
    del swig_import_helper
else:
    import _GsrSerDePyGen
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class read_only_byte_array(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, read_only_byte_array, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, read_only_byte_array, name)
    __repr__ = _swig_repr

    def __init__(self, data, p_err):
        this = _GsrSerDePyGen.new_read_only_byte_array(data, p_err)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _GsrSerDePyGen.delete_read_only_byte_array
    __del__ = lambda self: None

    def get_data(self):
        return _GsrSerDePyGen.read_only_byte_array_get_data(self)

    def get_len(self):
        return _GsrSerDePyGen.read_only_byte_array_get_len(self)
read_only_byte_array_swigregister = _GsrSerDePyGen.read_only_byte_array_swigregister
read_only_byte_array_swigregister(read_only_byte_array)

class mutable_byte_array(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mutable_byte_array, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mutable_byte_array, name)
    __repr__ = _swig_repr

    def __init__(self, len, p_err):
        this = _GsrSerDePyGen.new_mutable_byte_array(len, p_err)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _GsrSerDePyGen.delete_mutable_byte_array
    __del__ = lambda self: None

    def get_data_copy(self, data):
        return _GsrSerDePyGen.mutable_byte_array_get_data_copy(self, data)

    def get_data(self):
        return _GsrSerDePyGen.mutable_byte_array_get_data(self)

    def get_max_len(self):
        return _GsrSerDePyGen.mutable_byte_array_get_max_len(self)
mutable_byte_array_swigregister = _GsrSerDePyGen.mutable_byte_array_swigregister
mutable_byte_array_swigregister(mutable_byte_array)

class glue_schema_registry_schema(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, glue_schema_registry_schema, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, glue_schema_registry_schema, name)
    __repr__ = _swig_repr

    def __init__(self, schema_name, schema_def, data_format, additional_schema_info, p_err):
        this = _GsrSerDePyGen.new_glue_schema_registry_schema(schema_name, schema_def, data_format, additional_schema_info, p_err)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _GsrSerDePyGen.delete_glue_schema_registry_schema
    __del__ = lambda self: None

    def get_schema_name(self):
        return _GsrSerDePyGen.glue_schema_registry_schema_get_schema_name(self)

    def get_schema_def(self):
        return _GsrSerDePyGen.glue_schema_registry_schema_get_schema_def(self)

    def get_data_format(self):
        return _GsrSerDePyGen.glue_schema_registry_schema_get_data_format(self)

    def get_additional_schema_info(self):
        return _GsrSerDePyGen.glue_schema_registry_schema_get_additional_schema_info(self)
glue_schema_registry_schema_swigregister = _GsrSerDePyGen.glue_schema_registry_schema_swigregister
glue_schema_registry_schema_swigregister(glue_schema_registry_schema)

class glue_schema_registry_serializer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, glue_schema_registry_serializer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, glue_schema_registry_serializer, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _GsrSerDePyGen.new_glue_schema_registry_serializer(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _GsrSerDePyGen.delete_glue_schema_registry_serializer
    __del__ = lambda self: None

    def encode(self, array, transport_name, gsr_schema, p_err):
        return _GsrSerDePyGen.glue_schema_registry_serializer_encode(self, array, transport_name, gsr_schema, p_err)
glue_schema_registry_serializer_swigregister = _GsrSerDePyGen.glue_schema_registry_serializer_swigregister
glue_schema_registry_serializer_swigregister(glue_schema_registry_serializer)

class glue_schema_registry_deserializer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, glue_schema_registry_deserializer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, glue_schema_registry_deserializer, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _GsrSerDePyGen.new_glue_schema_registry_deserializer(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _GsrSerDePyGen.delete_glue_schema_registry_deserializer
    __del__ = lambda self: None

    def decode(self, array, p_err):
        return _GsrSerDePyGen.glue_schema_registry_deserializer_decode(self, array, p_err)

    def can_decode(self, array, p_err):
        return _GsrSerDePyGen.glue_schema_registry_deserializer_can_decode(self, array, p_err)

    def decode_schema(self, array, p_err):
        return _GsrSerDePyGen.glue_schema_registry_deserializer_decode_schema(self, array, p_err)
glue_schema_registry_deserializer_swigregister = _GsrSerDePyGen.glue_schema_registry_deserializer_swigregister
glue_schema_registry_deserializer_swigregister(glue_schema_registry_deserializer)


def glue_schema_registry_set_config_file(config_file_path, p_err):
    return _GsrSerDePyGen.glue_schema_registry_set_config_file(config_file_path, p_err)
glue_schema_registry_set_config_file = _GsrSerDePyGen.glue_schema_registry_set_config_file
# This file is compatible with both classic and new-style classes.


